[package]
name = "error_gamma"
version = "0.1.0"
authors = ["Cazadorro"]
edition = "2018"
categories  = ["mathematics"]
keywords    = ["math"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
